from typing import Any, Callable


class Limiter:
    def __init__(self, key_func: Callable[..., Any] | None = None, app: Any | None = None, **kwargs: Any) -> None: ...
    def init_app(self, app: Any) -> None: ...
    def limit(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
