all:
  hosts:
    questbycycle:
      ansible_host: <PUBLIC_IP_FROM_TERRAFORM>
      ansible_user: <YOUR_OS_LOGIN_USER>
      ansible_ssh_private_key_file: <YOUR_KEY>
      ansible_ssh_extra_args: "-o 'IdentitiesOnly yes' -o 'StrictHostKeyChecking=no'"
      ansible_become: yes
      ansible_become_method: sudo
