from typing import Any, Iterable


class Humanify:
    has_valid_clearance_token: bool

    def __init__(self, challenge_type: str = ...) -> None: ...
    def init_app(self, app: Any) -> None: ...
    def register_middleware(self, action: str, endpoint_patterns: Iterable[str]) -> None: ...
    def challenge(self) -> Any: ...
