name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install --no-interaction
      - name: Install Node dependencies
        run: |
          npm install
          npm run build
      - name: Run tests
        run: |
          poetry run env PYTHONPATH="$PWD" pytest -q
